name: dahttp
description: HTTP wrapper for Dart with integrated logger design to be used for REST APIs.
version: 3.3.0
homepage: https://github.com/mauriciotogneri/dahttp

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.3