name: dahttp
description: HTTP wrapper for Dart with integrated logger design to be used for REST APIs.
version: 3.0.1
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dahttp

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.6.4